package com.unistra.m2info.composemymeal

val countryIconMap = mapOf(
    "French" to R.drawable.france,
    "Italian" to R.drawable.italy,
    "Spanish" to R.drawable.spain,
    "Japanese" to R.drawable.japan,
    "Indian" to R.drawable.india,
    "Mexican" to R.drawable.mexico,
    "American" to R.drawable.unitedstates,
    "British" to R.drawable.unitedkingdom,
    "Canadian" to R.drawable.canada,
    "Chinese" to R.drawable.china,
    "Croatian" to R.drawable.croatia,
    "Dutch" to R.drawable.germany,
    "Egyptian" to R.drawable.egypt,
    "Filipino" to R.drawable.philippines,
    "Greek" to R.drawable.greece,
    "Irish" to R.drawable.ireland,
    "Jamaican" to R.drawable.jamaica,
    "Kenyan" to R.drawable.kenya,
    "Malaysian" to R.drawable.malaysia,
    "Moroccan" to R.drawable.morocco,
    "Polish" to R.drawable.poland,
    "Portuguese" to R.drawable.portugal,
    "Russian" to R.drawable.russia,
    "Thai" to R.drawable.thailand,
    "Tunisian" to R.drawable.tunisia,
    "Turkish" to R.drawable.turkey,
    "Ukrainian" to R.drawable.ukraine,
    "Vietnamese" to R.drawable.vietnam
)
